build:
	g++ -Wall -Wextra -Werror poduri.cpp -o poduri
	g++ -Wall -Wextra -Werror adrese.cpp -o adrese
	g++ -Wall -Wextra -Werror lego.cpp -o lego
	g++ -Wall -Wextra -Werror retea.cpp -o retea
run-p1: poduri
	./poduri
run-p2: adrese
	./adrese
run-p3: lego
	./lego
run-p4: retea
	./retea
clean:
	rm poduri adrese lego retea