build:
	g++ -Wall -Wextra -Werror crypto.cpp -o crypto
	g++ -Wall -Wextra -Werror stocks.cpp -o stocks
	g++ -Wall -Wextra -Werror valley.cpp -o valley
	g++ -Wall -Wextra -Werror ridge.cpp -o ridge
	g++ -Wall -Wextra -Werror trigigel.cpp -o trigigel
run-p1: crypto
	./crypto
run-p2: stocks
	./stocks
run-p3: valley
	./valley
run-p4: ridge
	./ridge
run-p5: trigigel
	./trigigel
clean:
	rm crypto stocks valley ridge trigigel